import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets:["latin"],
  weight: ["400", "500"]
})

const pop_reg = localFont({
  src: "../public/fonts/Poppins-Regular.ttf",
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pop_reg.variable}>{children}</body>
    </html>
  );
}
